# just a sample
web:
  image: 'imjing/react-demo'
  tty: true
  ports:
    - 80/tcp
  environment:
    - NGINX_HOST=react-demo.com
    - NGINX_PORT=80
    - REWRITE_ROOT_PATH=no_rewirte_root
  command: /bin/bash -c "envsubst '$$NGINX_HOST$$NGINX_PORT' < /etc/nginx/conf.d/server.conf  > /etc/nginx/conf.d/default.conf && nginx -g 'daemon off;'"
  restart: always
  labels:
    aliyun.scale: '1'
    aliyun.routing.port_80: 'http://zuul-admin-ut.nakedhub.com'
  memswap_limit: 0
  mem_limit: 0
  shm_size: 0
  # memswap_reservation: 0
  # kernel_memory: 0
  # name: web